server_name: auth-callout-integration
port: 4222
http_port: 8222

authorization {
  timeout: 2s
  users: [
    { user: auth_callout, password: local-callout-only, permissions: { publish: ["$SYS._INBOX.>"], subscribe: ["$SYS.REQ.USER.AUTH"] } }
    { user: auth_echo, password: local-echo-only, permissions: { publish: ["_INBOX.>"], subscribe: ["auth.echo"] } }
  ]
  auth_callout {
    issuer: "ABJHLOVMPA4CI6R5KLNGOB4GSLNIY7IOUPAJC4YFNDLQVIOBYQGUWVLA"
    auth_users: [auth_callout, auth_echo]
  }
}
max_payload: 1048576
write_deadline: "5s"
